version: 0.1 ({build})
skip_branch_with_pr: true

image:
- Visual Studio 2017

platform:
- x64

configuration:
- Release

clone_folder: C:\Gear

before_build:
  - cd C:\Gear
  - git submodule update --init --recursive
  - cd C:\Gear\scripts
  - Win-GenProjects.bat && cd C:\Gear

build:
  project: C:\Gear\Gear.sln
  parallel: true
  verbosity: normal